Create xAB Functional Content.py
labs4capella/python4capella pull request #195
Opened 2023-11-13 18:24 UTC by Sophie-Pl

2023-11-14 08:09 UTC, ylussaud requested changes
Small changes needed in the comments.

2023-11-14 08:09 UTC, ylussaud commented on plugins/Python4Capella/sample_scripts/xAB Functional Content.py
> +# To run it:
To run it you need to right click on a DRepresentationDescriptor (diagram in the project explorer ?) and select the "Extract content of xAB diagram" menu.

2023-11-14 08:09 UTC, ylussaud commented on plugins/Python4Capella/sample_scripts/xAB Functional Content.py
> +This script allows to exxtract content of xAB diagram
exxtract -> extract

2023-11-15 13:09 UTC, Sophie-Pl reviewed
Ok for the modifications to add in comments

2023-11-15 16:58 UTC, Sophie-Pl commented
I reopen the pull request in order to merge the script xAB functional content (update after review)

2023-11-22 08:23 UTC, merged